apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: kubernetes
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps
    targetPort: 21
    protocol: TCP
  - port: 20100
    name: port-passv
    protocol: TCP
    targetPort: 20100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20100