apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: kubernetes
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress